layout:
  - 'layout/**/*'

page:
  - 'pages/**/*'

component:
  - 'components/**/*'

config:
  - 'config/**/*'

plugin:
  - 'plugin/**/*'

store:
  - 'store/**/*'

middleware:
  - 'middleware/**/*'

content:
  - 'content/**/*'

assets:
  - 'assets/**/**/*'
  - 'assets/**/*'
  - 'assets/*'

static-assets:
  - 'static/**/**/*'
  - 'static/**/*'
  - 'static/*'

github-actions:
  - '.github/*'
  - '.github/**/*'

app-config: 
  - nuxt.config.js

dependencies: 
  - package.json
  - package-lock.json

documentation: 
  - README.md
  - '**/README.md'
