# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Check spelling
        # You may pin to the exact commit or the version.
        # uses: check-spelling/check-spelling@ead83f4596b4aac06f698b501b5beb3218f6214d
        uses: check-spelling/check-spelling@0.0.17-alpha
#         with:
          # The GITHUB_TOKEN secret
#           GITHUB_TOKEN: # default is ${{ github.token }}
          # Container for spelling configuration
#           bucket: # optional
          # Folder/Branch within bucket containing spelling configuration
#           project: # optional
          # Spelling configuration directory
#           config: # optional, default is .github/actions/spelling
          # Location of dictionary (if you aren't providing one in your repository)
#           dictionary_url: # optional, default is https://raw.githubusercontent.com/check-spelling/check-spelling/dictionary-$DICTIONARY_VERSION/dict.txt
          # Version of the dictionary (only used if the url includes $DICTIONARY_VERSION)
#           dictionary_version: # optional, default is 20200211
          # Debug
#           debug: # optional
